/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author bmetin
 */
public class BuyFrame extends javax.swing.JFrame {

    Connection con = null;
    Statement st;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String totalPrice;
    /**
     * Creates new form BuyFrame
     */
    public BuyFrame(String totalPrice) {
        initComponents();
        this.totalPrice=totalPrice;
        totalText.setText(totalPrice);
        
    }
    

    
    public void calculatePrice()
    {
         try{
      
        
           con = Connections.getConnection();
           st = con.createStatement();
           
           String searchQuery = " SELECT SUM (PRICE) FROM PRODUCT;";
          
           st.executeQuery(searchQuery); 
           
       }catch(Exception e)
       {
           
           System.out.println(e.getMessage());
       }
    
    }
    
    public void insertCustomerAddress()
    {
      
       //String e_address = addressText.getText();
       
       try{
      
        
           con = Connections.getConnection();
           st = con.createStatement();
           
           String searchQuery = "INSERT INTO CARGO_ADDRESS(ADDRESS) VALUES('"+addressText.getText()+"') ";
          
           st.executeQuery(searchQuery); 
           
       }catch(Exception e)
       {
           
           System.out.println(e.getMessage());
       }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        buyLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cargoLabel = new javax.swing.JLabel();
        cargoText = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        continueButton = new javax.swing.JButton();
        finalTotalLabel = new javax.swing.JLabel();
        finalTotalText = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainTitle.setFont(new java.awt.Font("Viner Hand ITC", 1, 80)); // NOI18N
        mainTitle.setText("HARMONIA");
        getContentPane().add(mainTitle);
        mainTitle.setBounds(390, 30, 560, 110);

        buyLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        buyLabel.setText("Order info:");
        getContentPane().add(buyLabel);
        buyLabel.setBounds(580, 170, 330, 50);

        addressLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addressLabel.setText("ADDRESS : ");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(590, 270, 90, 40);

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        getContentPane().add(addressText);
        addressText.setBounds(770, 250, 310, 90);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(490, 400, 720, 20);

        cargoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cargoLabel.setText("CARGO :");
        getContentPane().add(cargoLabel);
        cargoLabel.setBounds(590, 490, 60, 20);

        cargoText.setText("        7 TL");
        cargoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoTextActionPerformed(evt);
            }
        });
        getContentPane().add(cargoText);
        cargoText.setBounds(680, 480, 80, 30);

        totalLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalLabel.setText("TOTAL :");
        getContentPane().add(totalLabel);
        totalLabel.setBounds(590, 560, 60, 30);
        getContentPane().add(totalText);
        totalText.setBounds(680, 560, 90, 30);

        continueButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        continueButton.setText("CONTINUE");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continueButton);
        continueButton.setBounds(940, 620, 190, 50);

        finalTotalLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        finalTotalLabel.setText("Final Total:");
        getContentPane().add(finalTotalLabel);
        finalTotalLabel.setBounds(950, 510, 80, 30);

        finalTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalTotalTextActionPerformed(evt);
            }
        });
        getContentPane().add(finalTotalText);
        finalTotalText.setBounds(1050, 510, 100, 30);

        checkButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        checkButton.setText("CHECK");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton);
        checkButton.setBounds(810, 510, 110, 40);

        mainButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        mainButton.setText("GO MAIN PAGE");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainButton);
        mainButton.setBounds(60, 60, 250, 60);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1290, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        
    }//GEN-LAST:event_addressTextActionPerformed

    private void cargoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoTextActionPerformed
        
    }//GEN-LAST:event_cargoTextActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if(addressText.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "You did not enter an address ! Please enter address.");
        }
        else 
        {
            insertCustomerAddress();
            ContinueFrame cF = new ContinueFrame(finalTotalText.getText());
            cF.setVisible(true);
        }
      
        
    }//GEN-LAST:event_continueButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
       
         int price = Integer.parseInt(totalText.getText());
        
        if(price > 100)
        {
            finalTotalText.setText(totalPrice);
        }
        
        else if(price < 100)
        {
            price = price + 7;
            //String finalTotalPrice = Integer.toString(price);
            finalTotalText.setText(Integer.toString(price));
        }
        
    }//GEN-LAST:event_checkButtonActionPerformed

    private void finalTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalTotalTextActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        SecondFrame sF = new SecondFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_mainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Creabackgrounddisplay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyFrame("totalPrice").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel background;
    private javax.swing.JLabel buyLabel;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JTextField cargoText;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel finalTotalLabel;
    private javax.swing.JTextField finalTotalText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainButton;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
