/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

import javax.swing.JOptionPane;

/**
 *
 * @author bmetin
 */
public class ContinueFrame extends javax.swing.JFrame {

    String finalPrice;
    /**
     * Creates new form ContinueFrame
     */
    public ContinueFrame(String finalPrice) {
        initComponents();
        this.finalPrice=finalPrice;
        calculatePoint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPageButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pointText = new javax.swing.JTextField();
        warning = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainPageButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        mainPageButton.setText("GO MAIN PAGE");
        mainPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainPageButton);
        mainPageButton.setBounds(70, 80, 260, 70);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setText("ORDER IS COMPLETED !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 260, 340, 60);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setText("Your order is being prepared . ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 370, 330, 40);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel3.setText("Your point:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 460, 120, 50);
        getContentPane().add(pointText);
        pointText.setBounds(810, 470, 230, 50);

        warning.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        warning.setText("* Your point will be available for 1 year.");
        getContentPane().add(warning);
        warning.setBounds(810, 540, 460, 40);

        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1320, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageButtonActionPerformed
        SecondFrame sF = new SecondFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_mainPageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContinueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContinueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContinueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContinueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContinueFrame("finalPrice").setVisible(true);
            }
        });
    }
    
    public void calculatePoint()
    {
        JOptionPane.showMessageDialog(null, "Product change/return is not allowed !");
       
        int priceInt = Integer.parseInt(finalPrice);
        System.out.println(priceInt);
        float point = (float)priceInt * 0.1f;
        System.out.println(point);
        
       
        pointText.setText(String.valueOf(point));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mainPageButton;
    private javax.swing.JTextField pointText;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
