/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author bmetin
 */
public class FirstJFrame extends javax.swing.JFrame {

    
    static Connection con;
    static ResultSet rs;
    static PreparedStatement ps;
    static Statement stm;
    
    public String a;
    
    /**
     * Creates new form cosmetic_market
     */
    public FirstJFrame() {
        initComponents();
        //dbConnection();
    }
/*
    public Connection dbConnection()
    {
         try {

            Class.forName("oracle.jdbc.OracleDriver");

            System.out.println("Connection to Database...");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","bm","bmlab");
            return null;
        }

        catch (Exception ex)
        {
            System.out.println("Exception: " + ex.getMessage() + "");
            return null;
        }
    }
    
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new javax.swing.JLabel();
        Go = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 700));
        getContentPane().setLayout(null);

        gif.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\giphy.gif")); // NOI18N
        gif.setPreferredSize(new java.awt.Dimension(700, 281));
        getContentPane().add(gif);
        gif.setBounds(620, 220, 500, 240);

        Go.setFont(new java.awt.Font("Viner Hand ITC", 0, 40)); // NOI18N
        Go.setText("GO ON !");
        Go.setToolTipText("");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        getContentPane().add(Go);
        Go.setBounds(950, 520, 163, 73);

        title.setFont(new java.awt.Font("Viner Hand ITC", 0, 100)); // NOI18N
        title.setText("HARMONIA");
        title.setToolTipText("HARMONIA\n");
        getContentPane().add(title);
        title.setBounds(560, 90, 680, 130);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 50)); // NOI18N
        jLabel1.setText("WELCOME ...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 290, 520, 130);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1300, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed

        SecondFrame sJ = new SecondFrame();
        
        sJ.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_GoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Go;
    private javax.swing.JLabel background;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
