/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author bmetin
 */
public class loginFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
   

    Statement st;
     ResultSet rs;
     PreparedStatement pst;
    
    public loginFrame() {
        initComponents();
        emailFi.setText(emailFi.getText());
        passFi.setText(passFi.getText());
    }
    
    
    private void check() {
        
        try {
            
            try (
                
                Connection con = Connections.getConnection()) {
                String sql = "SELECT * FROM REGISTER WHERE EMAIL = ? AND PASSWORD = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1,emailFi.getText());
                pst.setString(2,passFi.getText());
                
                rs = pst.executeQuery();
                
                if(rs.next()) {
                    
                    JOptionPane.showMessageDialog(null,"You logged in successfully");
                }                
                else {
                    JOptionPane.showMessageDialog(null,"Wrong password!");
                    emailFi.setText("");
                    passFi.setText("");
                }
                con.close();
            }
            
        }
        catch(SQLException e) {
            
            System.out.println(e);
        }
    }
    
    private void checkEmail() {
        
        try {
            
            try (Connection con = Connections.getConnection()) {
                String sql = "SELECT * FROM REGISTER WHERE EMAIL = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1,emailFi.getText());
                
                rs = pst.executeQuery();
                
                if(rs.next()) {
                    
                    
                }  
                else {
                    JOptionPane.showMessageDialog(null,"E-mail  doesn’t exist in the system.");
                }
                
            }
            
        }
        catch(SQLException e) {
            
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        emailFi = new javax.swing.JTextField();
        passFi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        goMainButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Viner Hand ITC", 1, 70)); // NOI18N
        title.setText("HARMONIA");
        getContentPane().add(title);
        title.setBounds(550, 90, 570, 110);

        subTitle.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        subTitle.setText("LOGIN");
        getContentPane().add(subTitle);
        subTitle.setBounds(640, 280, 340, 70);
        getContentPane().add(emailFi);
        emailFi.setBounds(650, 390, 360, 30);
        getContentPane().add(passFi);
        passFi.setBounds(650, 490, 360, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setText("Email Address:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 370, 220, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 470, 190, 20);

        goMainButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        goMainButton.setText("GO MAIN PAGE");
        goMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goMainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(goMainButton);
        goMainButton.setBounds(80, 110, 250, 50);

        loginButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(890, 610, 130, 40);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1290, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        checkEmail();
       
        check();
        
        SecondFrame sF = new SecondFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void goMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goMainButtonActionPerformed
        SecondFrame sF = new SecondFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_goMainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailFi;
    private javax.swing.JButton goMainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passFi;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
