/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

/**
 *
 * @author bmetin
 */
public class SecondFrame extends javax.swing.JFrame {

    String productT;
    
    /**
     * Creates new form SecondFrame
     */
    public SecondFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lipstick = new javax.swing.JLabel();
        lipImage = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        eyePencilLabel = new javax.swing.JLabel();
        eyePencilImageLabel = new javax.swing.JLabel();
        goButtonLip = new javax.swing.JToggleButton();
        goButtonEyePencil = new javax.swing.JToggleButton();
        foundationLabel = new javax.swing.JLabel();
        foundationImageLabel = new javax.swing.JLabel();
        goButtonFoundation = new javax.swing.JButton();
        mascaraLabel = new javax.swing.JLabel();
        mascaraImageLabel = new javax.swing.JLabel();
        goButtonMascara = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lipstick.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lipstick.setText("LIPSTICK");
        lipstick.setToolTipText("");
        getContentPane().add(lipstick);
        lipstick.setBounds(550, 190, 110, 40);

        lipImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\lip.jpg")); // NOI18N
        lipImage.setText("jLabel2");
        lipImage.setToolTipText("");
        getContentPane().add(lipImage);
        lipImage.setBounds(550, 240, 90, 110);

        createAccountButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        createAccountButton.setText("CREATE ACCOUNT");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createAccountButton);
        createAccountButton.setBounds(1060, 40, 150, 40);

        eyePencilLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        eyePencilLabel.setText("EYE PENCIL");
        getContentPane().add(eyePencilLabel);
        eyePencilLabel.setBounds(690, 190, 140, 40);

        eyePencilImageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\eyeP.jpg")); // NOI18N
        getContentPane().add(eyePencilImageLabel);
        eyePencilImageLabel.setBounds(710, 240, 100, 100);

        goButtonLip.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        goButtonLip.setText("GO");
        goButtonLip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonLipActionPerformed(evt);
            }
        });
        goButtonLip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                goButtonLipKeyReleased(evt);
            }
        });
        getContentPane().add(goButtonLip);
        goButtonLip.setBounds(560, 380, 70, 40);

        goButtonEyePencil.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        goButtonEyePencil.setText("GO");
        goButtonEyePencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonEyePencilActionPerformed(evt);
            }
        });
        getContentPane().add(goButtonEyePencil);
        goButtonEyePencil.setBounds(720, 380, 70, 40);

        foundationLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        foundationLabel.setText("FOUNDATION");
        getContentPane().add(foundationLabel);
        foundationLabel.setBounds(860, 190, 140, 40);

        foundationImageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\foundation.jpg")); // NOI18N
        getContentPane().add(foundationImageLabel);
        foundationImageLabel.setBounds(860, 250, 100, 90);

        goButtonFoundation.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        goButtonFoundation.setText("GO");
        goButtonFoundation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonFoundationActionPerformed(evt);
            }
        });
        getContentPane().add(goButtonFoundation);
        goButtonFoundation.setBounds(860, 380, 70, 40);

        mascaraLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        mascaraLabel.setText("MASCARA");
        getContentPane().add(mascaraLabel);
        mascaraLabel.setBounds(1030, 190, 120, 40);

        mascaraImageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\mascara.jpg")); // NOI18N
        getContentPane().add(mascaraImageLabel);
        mascaraImageLabel.setBounds(1020, 250, 110, 100);

        goButtonMascara.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        goButtonMascara.setText("GO");
        goButtonMascara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonMascaraActionPerformed(evt);
            }
        });
        getContentPane().add(goButtonMascara);
        goButtonMascara.setBounds(1030, 380, 70, 40);

        backButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(90, 650, 160, 40);

        loginButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginButton.setText("GO LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(1060, 100, 150, 40);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 70)); // NOI18N
        jLabel1.setText("HARMONIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 40, 530, 90);

        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        backgroundLabel.setText("jLabel1");
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1260, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonLipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonLipActionPerformed
       
        ThirdFrame tF = new ThirdFrame(lipstick.getText());
        tF.setVisible(true);      
        
    }//GEN-LAST:event_goButtonLipActionPerformed

    private void goButtonEyePencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonEyePencilActionPerformed
      
        ThirdFrame tF = new ThirdFrame(eyePencilLabel.getText());
        tF.setVisible(true);
    }//GEN-LAST:event_goButtonEyePencilActionPerformed

    private void goButtonFoundationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonFoundationActionPerformed
     
        ThirdFrame tF = new ThirdFrame(foundationLabel.getText());
        tF.setVisible(true);
    }//GEN-LAST:event_goButtonFoundationActionPerformed

    private void goButtonMascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonMascaraActionPerformed
     
        ThirdFrame tF = new ThirdFrame(mascaraLabel.getText());
        tF.setVisible(true);
    }//GEN-LAST:event_goButtonMascaraActionPerformed

    private void goButtonLipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goButtonLipKeyReleased
   
    }//GEN-LAST:event_goButtonLipKeyReleased

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        FirstJFrame fF = new FirstJFrame();
        fF.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        registerFrame rf=new registerFrame();
        rf.setVisible(true);
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        loginFrame lF=new loginFrame();
        lF.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel eyePencilImageLabel;
    private javax.swing.JLabel eyePencilLabel;
    private javax.swing.JLabel foundationImageLabel;
    private javax.swing.JLabel foundationLabel;
    private javax.swing.JToggleButton goButtonEyePencil;
    private javax.swing.JButton goButtonFoundation;
    private javax.swing.JToggleButton goButtonLip;
    private javax.swing.JButton goButtonMascara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lipImage;
    private javax.swing.JLabel lipstick;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mascaraImageLabel;
    private javax.swing.JLabel mascaraLabel;
    // End of variables declaration//GEN-END:variables
}
