/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author bmetin
 */
public class ThirdFrame extends javax.swing.JFrame {
    
    String productType;
    
    Statement st;
    ResultSet rs; 
    
    BasketFrame bF = new BasketFrame();
    
    /**
     * Creates new form SecondJFrame
     */
    /*
    public ThirdFrame() {
        initComponents();
        findBrand();
    }
    */
    
    public ThirdFrame()
    {
        
        initComponents();
        //tableSet();
        getConnection();
        findBrand();
    }
    
    
    public ThirdFrame(String productType)
    {
        this.productType = productType;
        //BasketFrame bF = new BasketFrame(productType);
        initComponents();
        getConnection();
        productTypeLabel.setText(productType);
        //findBrand();
       
    }
    
    

    public Connection getConnection()
    {
        Connection con = null;
         try {
            
            Class.forName("oracle.jdbc.OracleDriver");
            System.out.println("Connection to Database...");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SOFTWARE_PRO","bmetin1");
          
        }

        catch (Exception ex)
        {
            System.out.println("Exception: " + ex.getMessage() + "");
        
        }
         return con;
    }
    
    public ArrayList<Product> ListBrand()
    {
        
        ArrayList<Product> productLists;
        productLists = new ArrayList<>();
        
        //type = inputSearchText.getText();
       try{
      
        System.out.println("merhaba");
     
           Connection con = getConnection();
           st = con.createStatement();
           String searchQuery = "SELECT * FROM PRODUCT,BRAND WHERE TYPE='"+productTypeLabel.getText()+"' AND B_NAME ='"+inputSearchText.getText()+"' AND PRODUCT.BRAND_ID=BRAND.BRAND_ID ";
           rs = st.executeQuery(searchQuery); 
          
           //Brand brand;
           Product product;
           
           while(rs.next())
           {
                product=new Product(
                        rs.getInt("PRODUCT_ID"),
                        rs.getString("P_NAME"),
                        rs.getString("TYPE"),
                        rs.getInt("PRICE"),
                        rs.getString("EMAIL_ADDRESS"),
                        rs.getString("BRAND_ID"),
                        rs.getInt("STOCK_ID"),
                        rs.getInt("ORDER_ID"),
                        rs.getInt("STORE_ID")
                        
               );
              productLists.add(product);
           }
           //brandLists.add(brand);
       }catch(Exception e)
       {
           System.out.println(e.getMessage());
       }
       
       return productLists;
    }
    
    
    public void findBrand()
    {
        //ArrayList<Brand> brandL = ListBrand(inputSearchText.getText());
        ArrayList<Product> productL = ListBrand();
       
        
        DefaultTableModel model= new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"P_NAME","BRAND_ID","PRICE"});
        
        Object[]row=new Object[4];
        for(int i=0; i<productL.size(); i++)
        {
            row[0]=productL.get(i).getP_name();
            row[1]=productL.get(i).getBrand_id();
            row[2]=productL.get(i).getPrice();
            
        
            model.addRow(row);
        }
        
        searchTable.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        inputSearchText = new javax.swing.JTextField();
        listTable = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        backButton = new javax.swing.JToggleButton();
        productTypeLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JToggleButton();
        mainButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainTitle.setFont(new java.awt.Font("Viner Hand ITC", 0, 80)); // NOI18N
        mainTitle.setText("HARMONIA");
        getContentPane().add(mainTitle);
        mainTitle.setBounds(400, 30, 600, 100);

        inputSearchText.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        inputSearchText.setOpaque(false);
        inputSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchTextActionPerformed(evt);
            }
        });
        getContentPane().add(inputSearchText);
        inputSearchText.setBounds(570, 196, 450, 40);

        listTable.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "P_NAME", "BRAND_ID", "PRICE", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        searchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTableMouseClicked(evt);
            }
        });
        listTable.setViewportView(searchTable);

        getContentPane().add(listTable);
        listTable.setBounds(570, 340, 452, 170);

        backButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(60, 620, 140, 40);

        productTypeLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        getContentPane().add(productTypeLabel);
        productTypeLabel.setBounds(670, 150, 310, 30);

        searchButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(720, 250, 105, 30);

        mainButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        mainButton.setText("GO MAIN PAGE");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainButton);
        mainButton.setBounds(60, 50, 250, 60);

        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\SOFTWARE_PROJECT_COSMETIC\\software_database_images\\back3.jpg")); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1280, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchTextActionPerformed
        
    }//GEN-LAST:event_inputSearchTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       
        SecondFrame sJ = new SecondFrame();
        
        sJ.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
  
        findBrand();
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTableMouseClicked
        
        
        int index = searchTable.getSelectedRow();
        TableModel model1=searchTable.getModel();
        
        String product_name = model1.getValueAt(index, 0).toString();
        String brand_id = model1.getValueAt(index, 1).toString();
        String price = model1.getValueAt(index, 2).toString();
        
        bF.setVisible(true);
        bF.pack();
        bF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
       
        
        bF.productNameText.setText(product_name);
        bF.brandIdText.setText(brand_id);
        bF.priceText.setText(price);
       
        

    }//GEN-LAST:event_searchTableMouseClicked

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        SecondFrame sF = new SecondFrame();
        sF.setVisible(true);
    }//GEN-LAST:event_mainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdFrame("productType").setVisible(true);
                new ThirdFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField inputSearchText;
    private javax.swing.JScrollPane listTable;
    private javax.swing.JButton mainButton;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel productTypeLabel;
    private javax.swing.JToggleButton searchButton;
    private javax.swing.JTable searchTable;
    // End of variables declaration//GEN-END:variables
}
